### ISSUE TITLE
Error when using the theme

### ISSUE THREAD

**Issue by ligengli** [lazysheep666/terminal_theme#14]
Thanks for this nice theme. But when I use the theme, there is a error. Just like:

Unhandled rejection TypeError: /home/gengli/Documents/blog/change_face/themes/terminal/layout/includes/terminal.pug:28
    26|     span(class="code-pl-input") node #{fileName}.js
    27|     if theme.terminal[objName] !== null
  > 28|       each obj, key in theme.terminal[objName]
    29|         br
    30|         br
    31|         | > #{objName}.#{key}

Cannot read property 'length' of undefined
    at eval (eval at wrap (/home/gengli/Documents/blog/change_face/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:259:32)
    at eval (eval at wrap (/home/gengli/Documents/blog/change_face/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:352:4)
...........a lot

**Comment by bluecodecc** [comment]
I fixed this bug
